In [2]:
# LSTM for one-char to one-char prediction

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras import utils


In [3]:
import numpy as np 
np.random.seed(7)   # fix random seed for reproducibility

# define raw dataset
alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

# creating mapping of characters to integers (0 - 25) and reverse
char_to_int = dict((c , i) for i , c in enumerate(alphabet))
int_to_char = dict((i , c) for i , c in enumerate(alphabet))

In [4]:
char_to_int

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

In [6]:
len(alphabet)

26

# Data prepartion
preparing input and output data form raw dataset the data set must be sequential so that it can predict the value just after the input char

In [13]:
input_seq = 1 # This will decide after how many charecter the model will predict the next charcter
dataX = []  # For input sequence
dataY = []  # For output sequence

for i in range(len(alphabet)):
    seq_in = alphabet[i]
    if i == 25:
        seq_out = alphabet[0]
    else:
        seq_out = alphabet[i + input_seq]
    dataX.append([char_to_int[char] for char in seq_in])
    dataY.append([char_to_int[char] for char in seq_out])
    print( seq_in, '->', seq_out)

A -> B
B -> C
C -> D
D -> E
E -> F
F -> G
G -> H
H -> I
I -> J
J -> K
K -> L
L -> M
M -> N
N -> O
O -> P
P -> Q
Q -> R
R -> S
S -> T
T -> U
U -> V
V -> W
W -> X
X -> Y
Y -> Z
Z -> A


In [14]:
dataX

[[0],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [12],
 [13],
 [14],
 [15],
 [16],
 [17],
 [18],
 [19],
 [20],
 [21],
 [22],
 [23],
 [24],
 [25]]

In [15]:
dataY

[[1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [12],
 [13],
 [14],
 [15],
 [16],
 [17],
 [18],
 [19],
 [20],
 [21],
 [22],
 [23],
 [24],
 [25],
 [0]]

In [25]:
# Now we will Reshape the the input dataset and normalize it
# the the shape of the dataset after reshape will be [samples , input_sequence , features]
x = np.reshape(dataX , (len(dataX) , input_seq , 1))
# normalizing the dataset
x = x/float(len(alphabet))

# The output dataset will be "One_Hot_Encoded"
y = utils.to_categorical(dataY)

In [26]:
x.shape

(26, 1, 1)

In [27]:
x

array([[[0.        ]],

       [[0.03846154]],

       [[0.07692308]],

       [[0.11538462]],

       [[0.15384615]],

       [[0.19230769]],

       [[0.23076923]],

       [[0.26923077]],

       [[0.30769231]],

       [[0.34615385]],

       [[0.38461538]],

       [[0.42307692]],

       [[0.46153846]],

       [[0.5       ]],

       [[0.53846154]],

       [[0.57692308]],

       [[0.61538462]],

       [[0.65384615]],

       [[0.69230769]],

       [[0.73076923]],

       [[0.76923077]],

       [[0.80769231]],

       [[0.84615385]],

       [[0.88461538]],

       [[0.92307692]],

       [[0.96153846]]])

In [29]:
print(y.shape)
y

(26, 26)


array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

# Creating model Using LSTM

In [37]:
# creating model

model = Sequential()
model.add(LSTM(32 , input_shape=(x.shape[1], x.shape[2])))
# the input_shape is [number of sequence , number of features] 
model.add(Dense(y.shape[1], activation = 'softmax'))

In [38]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_4 (LSTM)                (None, 32)                4352      
_________________________________________________________________
dense_1 (Dense)              (None, 26)                858       
Total params: 5,210
Trainable params: 5,210
Non-trainable params: 0
_________________________________________________________________


In [39]:
# compiling the model and training on the input and output data
model.compile(
    optimizer= 'adam' , 
    loss= 'categorical_crossentropy',
    metrics= ['accuracy']
)

# training the model on the input and output dataset
model.fit(x ,y , batch_size= 1 , epochs= 500 , verbose= 2)

poch 162/500
26/26 - 0s - loss: 2.2652 - accuracy: 0.3462
Epoch 163/500
26/26 - 0s - loss: 2.2600 - accuracy: 0.3077
Epoch 164/500
26/26 - 0s - loss: 2.2581 - accuracy: 0.3846
Epoch 165/500
26/26 - 0s - loss: 2.2540 - accuracy: 0.3077
Epoch 166/500
26/26 - 0s - loss: 2.2506 - accuracy: 0.3462
Epoch 167/500
26/26 - 0s - loss: 2.2487 - accuracy: 0.2692
Epoch 168/500
26/26 - 0s - loss: 2.2458 - accuracy: 0.3077
Epoch 169/500
26/26 - 0s - loss: 2.2428 - accuracy: 0.2692
Epoch 170/500
26/26 - 0s - loss: 2.2416 - accuracy: 0.3462
Epoch 171/500
26/26 - 0s - loss: 2.2364 - accuracy: 0.3846
Epoch 172/500
26/26 - 0s - loss: 2.2344 - accuracy: 0.3462
Epoch 173/500
26/26 - 0s - loss: 2.2313 - accuracy: 0.3462
Epoch 174/500
26/26 - 0s - loss: 2.2279 - accuracy: 0.3462
Epoch 175/500
26/26 - 0s - loss: 2.2264 - accuracy: 0.3462
Epoch 176/500
26/26 - 0s - loss: 2.2218 - accuracy: 0.3846
Epoch 177/500
26/26 - 0s - loss: 2.2196 - accuracy: 0.3462
Epoch 178/500
26/26 - 0s - loss: 2.2164 - accuracy: 0.307

# Summerize performance of the model

In [40]:
scores = model.evaluate(x ,y, verbose = 1)
print("Model accuracy : % .2f%%" %(scores[1] * 100))

1/1 [==============================] - 0s 1ms/step - loss: 1.7204 - accuracy: 0.7692
Model accuracy :  76.92%


In [41]:
# Checking for one sample

test = dataX[4]
# reshaping the test data
test = np.reshape(test , (1 ,len(test) , 1))
# normalizing the dataset
test = test/len(alphabet)
pred = model.predict(test , verbose = 0)
pred

array([[9.00643015e-12, 2.84725782e-02, 5.92486449e-02, 1.12994425e-01,
        1.83565721e-01, 2.08272800e-01, 1.77453518e-01, 1.12904154e-01,
        6.56640679e-02, 3.01563516e-02, 1.29606519e-02, 5.40309958e-03,
        1.95575273e-03, 6.55078213e-04, 2.00513095e-04, 6.55767290e-05,
        2.03363943e-05, 5.06495371e-06, 1.25297913e-06, 3.39493255e-07,
        8.46008987e-08, 1.84368947e-08, 3.96883548e-09, 7.94589672e-10,
        1.51832713e-10, 4.70271495e-11]], dtype=float32)

In [49]:
ind = np.argmax(pred)
print("predicted value index : {}".format(ind))
res = int_to_char[ind]
print('The charactor after {0} is {1}'.format(int_to_char[4] , res))

predicted value index : 5
The charactor after E is F
